openapi: 3.0.0
info:
  title: 'Laravel and Swagger'
  description: 'Getting started with Laravel and Swagger'
  termsOfService: ''
  contact:
    email: name@example.com
  version: 1.0.0
schemes:
  - http
host: 'localhost:8000'
basePath: /
